%YAML:1.1
---
##########  AngleSolver  ##########
CAMERA_MATRIX: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [2385.27508341373, 0, 706.3992740188233,
     0, 2388.628439590787, 548.9891287751039,
     0, 0, 1]


DISTORTION_COEFF: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [0.06055295456945162, -4.14124115366316, -0.00243068226202482, -0.004122633276866059, 37.04189535760245]
  #畸变参数矩阵，k1,k2,k3,p1,p2。一定注意是k1,k2,k3,p1,p2!!!和ROS标出来的k1,k2,p1,p2,k3不同！！！
m_x_off: -140
m_y_off: 0
m_z_off: 40
m_yaw_off: 0.0
m_pitch_off: 0.0
m_chx_off: 0
m_chy_off: 0
m_chz_off: 0

##########  TrackState  ##########
m_RecognizedArmorNumber: 0
m_MaxTrackingDistance: 0.8
m_TrackingThreshold: 5.0
m_LostThreshold: 5.0
m_DetectCount_: 0
m_FrameCounter: 0
m_max_match_distance_: 80
allow_following_range: 0.3
max_jump_angle: 0.2
max_jump_period: 0.8
jump_period_: 0.0
jump_count_: 0
accutime: 0
spintime: 0

##########  PredictPitch  ##########
hr: -0.17
t: 0
theta: 0
dk: 0
v0x: 0
Y_r: 0.20
a: 0
theta_d: 0
Y_d: 0.42
X_d: 0.2